language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - ree
env:
  - "rack=1.3.4"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
before_install: "gem install bundler --pre"
script: "bundle exec rake travis:build"
bundler_args: "--without development production"
gemfile: gemfiles/Gemfile.ci